baseURL = "https://jun10000.github.io/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "Jun's GamingBlog"
theme = "cayman-hugo-theme"
hasCJKLanguage = true
summaryLength = 140
enableGitInfo = true

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = "Jun's GamingBlog"
  project_tagline = " "

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006/01/02"

  # If true, the CSS/JS for Katex math typesetting are enabled
  # katex = true

[menu]
  [[menu.nav]]
    name = "ブログ"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/jun10000"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.tableOfContents]
    ordered = true
    startLevel = 2
    endLevel = 3
